### ISSUE TITLE
Extension Names - Listing Validation

### ISSUE THREAD

**Issue by anibalsanchez** [joomla-extensions/jedchecker#110]
I've been testing the extensions with the recent improvements and they are working great. So, I have an idea about a new improvement that can greatly improve how we work today.

There is a complex issue around how to check the Extension Name and the matching Listing Name. Since they are entered on JED and the extensions manifests, they are frequently different and that's a big error that today can only be detected manually. **The problem affects 90% of the first extension submissions.**

The most common problem when we check the extension is that the developer submits a listing name "A1234" and then submits a zip file to install the extension name "BBBBBBB". In strict terms, even if the extension is named "A12 3" or "A12345", they are different names, then the extension is rejected and the developer has to fix the issue.

Additionally:

- The plugin naming case: "{Type} - {Extension Name}”
- The parent extension case: "{Extension Name} for {Parent Extension}”
- Use of the Word Joomla: “{Extension Name} for Joomla”

To solve the issue, I think that we must introduce a new mandatory field before the file upload **Listing Name**.

In this way, the Extension Checker can validate if the extension and sub-extensions installation names match the declared "Listing Name".

What do you think? Is it doable in the light of the recent improvements?

CC: @dryabov @Llewellynvdm

**Comment by Llewellynvdm** [comment]
This sounds okay, but what about packages, should they then add names for each extension in the package?

Further for me automation is always my goal as it is the future... and so can we not instead as part of the result "messages" instead of a field give a message that will say something like:

```txt
When adding this extension to the JED only the following name will be excepted,
provided that it is not already taken: Extension Name
```

This way they need not add a name, we tell them what should be the name based on the xml of the extensions. The wording can change and here we can do some validation if the name is in fact following good practice as @dryabov has already started to do in this https://github.com/joomla-extensions/jedchecker/pull/80

**Comment by Llewellynvdm** [comment]
We can make this message prominent so that it is noticeable.

**Comment by dryabov** [comment]
IMHO, it's better to display above message in the public JEDChecker component, and as to the internal one, it's better to implement an events system in JEDChecker (e.g. `onJEDCheckerCheckListingName($report, $listingName)`), so that it will be possible to implement extra checks in `jedCheckCLI`.

**Comment by anibalsanchez** [comment]
> This sounds okay, but what about packages, should they then add names for each extension in the package?

@Llewellynvdm Yes, packages must also match the listing name. The package name is only noticeable in the Extension Manager, but it must also match the Listing name (to avoid the case of installing the extension AAA and finding a package installed as BBB).

> can we not instead as part of the result "messages" instead of a field

@Llewellynvdm No, we need to do it prominently. The developers don't realize that the Listing Name is the same name that is declared in the manifests. The developers create the extensions well before submitting them, so they forget the assigned name or forget to think twice about the extension name. 

I think that a new field is the only way to make them think about the missing link. With the new field, we are going to make the developers wonder "why the JED Checker asks for the Listing Name to check it now?" 

Additionally, the new field **Listing name** field can help to validate the consistency of the declared manifest names. Sometimes, the developer applies the right name to the component and forget to check the plugins name. On top of that, most of the times, the Listing Specialist can't check all names of a big package in a reasonable time.

**Comment by dryabov** [comment]
Are there restrictions on the allowed characters (emoji, non-latin characters, zero-width space, etc.) and the length of extension's name?

**Comment by anibalsanchez** [comment]
The JED only allows English/Latin characters.

There were efforts to implement a part of the system with multi-lingual features (for instance, reviews). But, it is only partial support and the listings have to be in English.

**Comment by dryabov** [comment]
I've found a dozen of extension names with characters out of standard ASCII (32-127). Most of them are Extended Latin (ãéèíóúÜ), and two others are "´" and "®". So, it seems to be sufficient to allow "Basic Latin" and "Latin-1 Supplement" Unicode blocks only.

The question about maximal length is inspired by recent changes in Google Play rules: they reduced it from 50 to 30 characters. Currently the longest Joomla! extension name is "JEmbedAll embeds videos, images, documents and all you need for your website" (76 characters), but IMHO it's too much long.

**Comment by anibalsanchez** [comment]
The published extensions are not a good sample for standardization. In JED history, there has been a lot of changes and different criteria.
