### ISSUE TITLE
Rule XMLFILES - Wrong File not found

### ISSUE THREAD

**Issue by anibalsanchez** [joomla-extensions/jedchecker#112]
The new rule doesn't find the files when the extension is distributed on a package, with zipped files and the following files declaration:

```xml
	<files folder="components/com_sso">
		<filename>controller.php</filename>
		<filename>router.php</filename>
		<filename>sso.php</filename>
		<folder>controllers</folder>
		<folder>language</folder>
		<folder>models</folder>
		<folder>views</folder>
	</files>
```

**Comment by anibalsanchez** [comment]
CC @dryabov

**Comment by dryabov** [comment]
@anibalsanchez Is it part of xml manifest from zipped file? (I'm unable to reproduce it locally)

**Comment by Llewellynvdm** [comment]
Just add those xml values @anibalsanchez gave in his first post, and then run your test... this should not return xml not found.

**Comment by dryabov** [comment]
@Llewellynvdm It's exactly that I tried to do, see attachment:
[jedhecker_xmlfiles_test.zip](https://github.com/joomla-extensions/jedchecker/files/6423548/jedhecker_xmlfiles_test.zip)

**Comment by anibalsanchez** [comment]
I found the issue on one of the newly submitted extensions.

**Comment by dryabov** [comment]
> I found the issue on one of the newly submitted extensions.

Which one? Is it free (to download and test)?

**Comment by anibalsanchez** [comment]
I'm going to contact the developer to ask for his collaboration.

**Comment by anibalsanchez** [comment]
The developer gave me the :+1: to use the extension for JEDChecker testing.

**Comment by anibalsanchez** [comment]
@dryabov Have you been able to reproduce the issue on the extension? Can you solve it?

**Comment by Llewellynvdm** [comment]
I have merged the fix... lets test this to be sure.

**Comment by dryabov** [comment]
> @dryabov Have you been able to reproduce the issue on the extension? Can you solve it?

Yes, the problem was in duplicated extension's XML manifest located in admin directory. I've found that many other components have the same issue, and made a decision to exclude such files from analysis (see `$excludeList` in `JEDCheckerHelper::findManifests`). Further we could display a notice for these files (as Joomla! overwrites them by actual manifest from the root of the extension package), but for now I'd prefer to avoid such a false-positive.

**Comment by anibalsanchez** [comment]
Great. Today I'm processing extensions with the latest changes. After these tests, I guess we are ready to release the new version with all the new features.

**Comment by anibalsanchez** [comment]
I have opened a similar issue #131
