### ISSUE TITLE
Support of the JED Submission Error Codes

### ISSUE THREAD

**Issue by anibalsanchez** [joomla-extensions/jedchecker#155]
On the site, there is a general error coding system, the "Submission Error Codes": https://extensions.joomla.org/support/knowledgebase/item/submission-error-codes/

It is a quick way to refer to the error and classify the submission.

In the current UI, there is no easy way to associate the code with the error description.

Please, could you associate each error with a "Submission Error Code".

Thanks in advance.

CC: @dryabov

**Comment by Llewellynvdm** [comment]
Just a question, but was it not like this before? and why was this changed?

**Comment by anibalsanchez** [comment]
The JED Team is the main user of these error codes. The developers are not really used to PH1, NM1, LI1 or US.

In the previous UI, the error codes were always in the error description. Most people don't notice them.

![error-codes](https://user-images.githubusercontent.com/385780/132088983-df2fb47e-dd30-4e34-8a04-df6a229a9755.png)

**Comment by dryabov** [comment]
Most likely it's necessary to expand existing list of error codes to take into account new rules, e.g. "invalid language file", or "file not found" (for XMLFiles ruleset).

**Comment by Llewellynvdm** [comment]
Please use [this list as the bases](https://extensions.joomla.org/support/knowledgebase/item/submission-error-codes/), and add those new needed in this issue so we can in the next JED team meeting go over this as a team.

The next team meeting is this coming Friday the 10th of September.

**Comment by Llewellynvdm** [comment]
There can be **no next release** without this being fixed.

**Comment by dryabov** [comment]
What kind of design do you prefer?

**Comment by dryabov** [comment]
![2021-09-06 22_30_15-JED Checker - J4 0 Test - Administration](https://user-images.githubusercontent.com/378044/132256168-ae1a46d9-cd0b-4042-a0a8-98b9f6ec41b8.png)

**Comment by dryabov** [comment]
![2021-09-06 22_32_21-JED Checker - J4 0 Test - Administration](https://user-images.githubusercontent.com/378044/132256186-bc3ef13d-f690-4305-96c5-db533ef5d14f.png)

**Comment by dryabov** [comment]
![2021-09-06 22_34_18-JED Checker - J4 0 Test - Administration](https://user-images.githubusercontent.com/378044/132256198-880c831b-a3ac-43fb-a977-8efd1ffd06d5.png)

**Comment by JazParkyn** [comment]
> 
> 
> ![2021-09-06 22_30_15-JED Checker - J4 0 Test - Administration](https://user-images.githubusercontent.com/378044/132256168-ae1a46d9-cd0b-4042-a0a8-98b9f6ec41b8.png)

I prefer this option, but with an adjustement in the badge text. Change 'PH1 Error' to 'Error: PH1'. Then also implement the same format for info, warning and success badges too. Eg. 'Info: GPL' or 'Passed: US1'

**Comment by anibalsanchez** [comment]
Jaz recommendations are on the spot. 👍

**Comment by dryabov** [comment]
OK, the patch is added to the PR #157
