### ISSUE TITLE
Language file is not loaded, when lang prefix is missing.

### ISSUE THREAD

**Issue by n3t** [joomla-extensions/jedchecker#196]
Joomla 3.10 and 4.x supports non-prefixed language files, such as `plg_system_whatever.sys.ini`. Jed checker is trying to load only old-style prefixed file like `en-GB.plg_system_whatever.sys.ini`, so it is not able to load language constants from the extensions language file, and reports false positive errors in extension name check.

**Comment by dryabov** [comment]
Fixed in PR #210
