### ISSUE TITLE
Warning: syntax error, unexpected '{'  or '!'

### ISSUE THREAD

**Issue by peterhulst** [joomla-extensions/jedchecker#200]
When the language contains a { or an ! a warning is given with a syntax error:

**Warning: syntax error, unexpected '{' in  <file>
...administrator\components\com_jedchecker\libraries\rules\language.php on line 373**

This is due to parse_ini_file which does not allow the reserved characters in the key: {}|&~!()^"

The language file checks stops when such a character is found.

**Comment by dryabov** [comment]
Thank you! Fixed by PR #201.
