### ISSUE TITLE
NOTICE: Node <folder> has unknown attribute 'plugin' is wrong?

### ISSUE THREAD

**Issue by peterhulst** [joomla-extensions/jedchecker#202]
Hello, 
When validating plugin "contentnotifier" the XML Manifests has NOTICE: **Node <folder> has unknown attribute 'plugin'** is displayed.

This is for line: `<folder plugin="contentnotifier">services</folder>` in:

`<files>
			<folder plugin="contentnotifier">services</folder>
			<folder>language</folder>
			<folder>src</folder>
		</files>`

However removing plugin="contentnotifier" from that line giving:  `<folder>services</folder>`
gives during installation:

Plugin Install: Field 'element' doesn't have a default value
Error installing plugin

So I think that the NOTICE is wrong, because the plugin works correctly with: `<folder plugin="contentnotifier">services</folder>`

Regards,
Peter

**Comment by dryabov** [comment]
Fixed in PR #204 for plugins and modules (along with other related improvements)

**Comment by peterhulst** [comment]
I checked this and it works correctly now. Thank you!
