### ISSUE TITLE
Not recognized in XML: <name>language KEY</name>

### ISSUE THREAD

**Issue by peterhulst** [joomla-extensions/jedchecker#205]
When the plugin (or module name) is in the language file:
e.g. 
PCH_DESCRIPTION="Content - contentnotifier"
and the XML contains:
<name>PCH_DESCRIPTION</name>
The name displayed is the KEY and not the VALUE in the language file.
**The name tag in this file is: PCH_DESCRIPTION**
So the language string is not solved.

To display the correct name the entry in the XML should be:
<name>Content - contentnotifier</name>
Is it possible to correct this?

**Comment by dryabov** [comment]
Hmm, JEDChecker loads (at least should load) extension's .sys.ini file (see `loadExtensionLanguage` method: https://github.com/joomla-extensions/jedchecker/blob/develop/administrator/components/com_jedchecker/libraries/rules/xmlinfo.php#L276).

Could you send me (denis.ryabov at community.joomla.org) your extension to reproduce the issue?

**Comment by dryabov** [comment]
Try PR #210.

**Comment by peterhulst** [comment]
The PR #210 works perfectly! Thank you!
