### ISSUE TITLE
[J5] JED Checker extension only works with b/c plugin enabled

### ISSUE THREAD

**Issue by bayareajenn** [joomla-extensions/jedchecker#218]
In testing Official Joomla Extensions in J5, I found that the JED checker only works with the backward compatibility plugin enabled. 

Because it's an official J extension, it should work with the b/c plugin disabled too.

Here's a screenshot with debug on of how it looks with the b/c plugin disabled in J5a4 (nightlies).

![image](https://github.com/joomla-extensions/jedchecker/assets/5952595/591f149b-dac4-4641-a2de-b5bce1f53540)

**Comment by dryabov** [comment]
Yes, Joomla! 5.0 is not supported yet. I'm going to release JEDChecker 2.5 with J5 support after official release of Joomla! 5 Beta (approx. after September, 5) when we can be sure no significant changes will be made in API.

Currently it seems to be sufficient just to rename J-prefixed class names to "actual" class names, but I'll need to test it carefully.

**Comment by bayareajenn** [comment]
Great! Thanks @dryabov. I was just making sure it's on the list. <3

**Comment by sozzled** [comment]
Thanks for that information, Jenn.
