### ISSUE TITLE
Wrong deprecation:  Joomla\CMS\Filesystem\File and  Joomla\CMS\Filesystem\Folder ?

### ISSUE THREAD

**Issue by peterhulst** [joomla-extensions/jedchecker#244]
Hello,

When using JED Checker version 2.4.3 I got the following:

deprecated in Joomla! 5:
use Joomla\CMS\Filesystem\File;
Instead, use: \Joomla\Filesystem\File

deprecated in Joomla! 5:
use Joomla\CMS\Filesystem\Folder;
Instead, use: Joomla\Filesystem\Folder

**However  changing:** 
use Joomla\CMS\Filesystem\Folder; 
into: 
use Joomla\Filesystem\Folder;
gived both in J4 and J5:

_Call to undefined method Joomla\Filesystem\Folder::exists()_

I think both depreciation are wrongly indicated.

Regards

**Comment by dryabov** [comment]
They are deprecated, but not removed (the deprecation message is "will be removed in 6.0"). As far as I understand, it's recommended to use PHP's functions (is_dir, is_file) instead of a primitive wrappers around them.

**Comment by peterhulst** [comment]
Thank you for the reply.

In J5 you will find a lot of (> 60 matches):
use Joomla\CMS\Filesystem\Folder;

But: use Joomla\Filesystem\Folder;
can only be found 11 times.

So is J5 not consistent in that check?

**Comment by dryabov** [comment]
Most likely there are different people working on extensions and the library. As far as I remember, even Joomla 4 triggered a lot of deprecated messages in Alpha and Beta releases (that were only fixed in the RC version).
