### ISSUE TITLE
Obsolete language files

### ISSUE THREAD

**Issue by demis-palma** [joomla-extensions/jedchecker#35]
The source (English) language files has changed on the project, but they haven't been uploaded to Transifex.
As a result, both old and new translations are based on the outdated English version.

For example: the string COM_JEDCHECKER_RULE_PH1_DESC contains a [broken link](http://extensions.joomla.org/index.php?option=com_content&id=50) in the translations, while it contains a [valid link](http://extensions.joomla.org/support/knowledgebase/item/jed-entries-checklists#licensechecklist) in the project English language files.

It is required that the Transifex user "compojoom" runs the tx sync client. The translators will be automatically notified about the change.

**Comment by JazParkyn** [comment]
I'd like to re-write the English language strings before conversion. The English is some of them has grammar mistakes etc.

**Comment by JazParkyn** [comment]
I've been through the .ini files, but I believe that there are some places in the code where direct text has been used - instances of this should be replaced with language strings.

**Comment by miljan-aleksic** [comment]
Also the `COM_JEDCHECKER_ERROR_JAMSS_STRING` is missing in the language files.

**Comment by conconnl** [comment]
Looks like this issue was solved already.
Please close
