### ISSUE TITLE
Update server

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla-extensions/jedchecker#42]
In the extension XML the update server is still on compojoom.com .
It should be one of our servers.

**Comment by JazParkyn** [comment]
Thanks, will correct this evening. I will talk to compojoom to see if its possible enable a redirect so that users don't get stuck on 1.7

**Comment by jeckodevelopment** [comment]
Thanks!

**Comment by JazParkyn** [comment]
I have a draft ready, just need to complete tests on it, then will merge.

**Comment by conconnl** [comment]
Please close this is solved!
