### ISSUE TITLE
I am the administrator but have no rights :-)

### ISSUE THREAD

**Issue by jojo12** [joomla-extensions/jedchecker#44]
Trying to install JEDchecker on Joomla! 3.7.0 on php 7.1.3 as administrator, I get:
"You don't have permission to access /administrator/index.php on this server."
I was looking for information how to install, no such finds. Any help would be appreciated!

**Comment by jojo12** [comment]
I was trying above with the zip-file. On an other site I got:
there's no install !!!
Then I tried the other file (*.tar.gz) Installation worked properly.
There must be a problem inside the zip-file!

**Comment by jeckodevelopment** [comment]
I guess it's something with your server configuration.
