### ISSUE TITLE
Shouldn't assets be excluded?

### ISSUE THREAD

**Issue by alex7r** [joomla-extensions/jedchecker#46]
May be something like `assets` folder should be excluded from checks?

As for example use adding 3rd party library (TCPDF for example) will make extension not passing checks, or a lot of workarounds and code changes are needed?

**Comment by dryabov** [comment]
What if there is a backdoor in `assets` folder that is used by the main code? E.g.

    require  __DIR__ . '/assets/jquery.min.js';

(and `jquery.min.js` is a PHP code actually).

PS. Unfortunately, it looks like the JED Checker is not developed anymore, the last commit dated Apr 5, 2017.
