### ISSUE TITLE
False positives for encoding

### ISSUE THREAD

**Issue by WebsiteDons** [joomla-extensions/jedchecker#48]
The JED checker returns false positive for file encoding:
> You've used encoding in this file. This is not an error, but a JED editor will have to review this file

What does it see as encoding?
In the file there are comment lines written as //-------[ text here ]------/ and that's the only characters that differ.

**Comment by dryabov** [comment]
The encoding here means any occurrence of "base64" text, so that it results in false-positive for embedded images (i.e. `<img src="data:image/png;base64,...">`). Maybe it would be better to replace

    encodings ="base64"

by explicit

    encodings ="base64_encode,base64_decode"

in the encoding.ini file.

**Comment by dryabov** [comment]
Fixed in #170
