### ISSUE TITLE
DS is deprecated in Joomla 3

### ISSUE THREAD

**Issue by garstud** [joomla-extensions/jedchecker#58]
When checking my extension i show this *Compatibility Issue*
"**DS is deprecated in Joomla 3**"

But i always use the DS constant with another command at the begining of my code to be compatible with all Joomla versions:
`if (!defined('DS')) define('DS', DIRECTORY_SEPARATOR);`

Do am i right ?
If so, can you display the warning on 'DS' only if the constant is not defined ?

Thank you.

**Comment by anibalsanchez** [comment]
Hi,

No. DS must be removed from the code to follow deprecation.

The checker scans for the usage of the deprecated constants. The definition of the constant to support the newer versions of Joomla with the old source is not a case that we want to support. The deprecation of old coding practices must be followed to keep the code aligned with the modern code style.

Regards

**Comment by garstud** [comment]
Ok thank you for this explanation @anibalsanchez , i understand the reasons.

Do you have any good pratice about the use of DIRECTOY_SEPARATOR?
This constant name is very long and it is not easy to read code when you have a path with many DIRECTORY_SEPARATOR in it!
- Does anyone use another short name for "DIRECTORY_SEPARATOR"? 

`define('DRSP', DIRECTORY_SEPARATOR);`
Is this a solution that will follow the Joomla and JED coding styles?

Thank you if you can help me ;)

**Comment by anibalsanchez** [comment]
As far as I know, DIRECTORY_SEPARATOR is no longer necessary to define paths in modern PHP and the interpreter itself handled the differences between SOs.

**Comment by garstud** [comment]
Ok thank you for this info @anibalsanchez . 
Indeed, I found several information about this point:
https://alanhogan.com/tips/php/directory-separator-not-necessary
